package com.it342.basinillo.scheduler;

import com.it342.basinillo.entity.DemurrageLog;
import com.it342.basinillo.entity.DemurrageUrgency;
import com.it342.basinillo.entity.Shipment;
import com.it342.basinillo.repository.DemurrageLogRepository;
import com.it342.basinillo.service.EmailService;
import com.it342.basinillo.service.ShipmentService;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Transactional;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.temporal.ChronoUnit;
import java.util.List;

/**
 * Daily cron job that evaluates demurrage risk for all active shipments.
 *
 * Runs every day at 08:00 AM PHT (Asia/Manila = UTC+8 = 00:00 UTC).
 * For each overdue shipment, a {@link DemurrageLog} record is created
 * and an email alert is sent via {@link EmailService}.
 */
@Component
public class DemurrageScheduler {

    private static final Logger log = LoggerFactory.getLogger(DemurrageScheduler.class);
    private static final BigDecimal DEFAULT_DAILY_CHARGE = new BigDecimal("3000.00");

    private final ShipmentService shipmentService;
    private final DemurrageLogRepository demurrageLogRepository;
    private final EmailService emailService;

    public DemurrageScheduler(ShipmentService shipmentService,
                              DemurrageLogRepository demurrageLogRepository,
                              EmailService emailService) {
        this.shipmentService = shipmentService;
        this.demurrageLogRepository = demurrageLogRepository;
        this.emailService = emailService;
    }

    /**
     * Runs daily at 08:00 AM PHT (00:00 UTC).
     *
     * Evaluates every non-released, non-deleted shipment:
     *   1. Computes days remaining until doomsday.
     *   2. If overdue → creates a DemurrageLog entry.
     *   3. Sends email alerts for WARNING (≤3 days) and CRITICAL (≤0 days).
     */
    @Scheduled(cron = "0 0 0 * * *", zone = "Asia/Manila")
    @Transactional
    public void evaluateDemurrage() {
        log.info("Running daily demurrage evaluation...");

        List<Shipment> activeShipments = shipmentService.findActiveShipmentsForDemurrage();
        int alertsSent = 0;

        for (Shipment shipment : activeShipments) {
            if (shipment.getDoomsdayDate() == null) continue;

            long daysRemaining = ChronoUnit.DAYS.between(LocalDate.now(), shipment.getDoomsdayDate());
            DemurrageUrgency urgency = classifyUrgency(daysRemaining);

            // Create DemurrageLog for overdue shipments
            if (daysRemaining < 0) {
                createDemurrageLogEntry(shipment, daysRemaining);
            }

            // Send alerts for WARNING and CRITICAL shipments
            if (urgency != DemurrageUrgency.SAFE) {
                sendDemurrageAlert(shipment, daysRemaining, urgency);
                alertsSent++;
            }
        }

        log.info("Demurrage evaluation complete. {} shipments evaluated, {} alerts sent.",
                activeShipments.size(), alertsSent);
    }

    /* ================================================================== */
    /*  Private helpers                                                    */
    /* ================================================================== */

    private void createDemurrageLogEntry(Shipment shipment, long daysRemaining) {
        long overdueDays = Math.abs(daysRemaining);
        BigDecimal dailyCharge = DEFAULT_DAILY_CHARGE;
        BigDecimal cumulativeTotal = dailyCharge.multiply(BigDecimal.valueOf(overdueDays));

        DemurrageLog entry = DemurrageLog.builder()
                .shipment(shipment)
                .date(LocalDate.now())
                .chargeAmount(dailyCharge)
                .cumulativeTotal(cumulativeTotal)
                .notes("Auto-generated by daily cron. " + overdueDays + " day(s) overdue.")
                .build();

        demurrageLogRepository.save(entry);
    }

    private void sendDemurrageAlert(Shipment shipment, long daysRemaining, DemurrageUrgency urgency) {
        String brokerEmail = shipment.getAssignedBroker() != null
                ? shipment.getAssignedBroker().getEmail() : null;

        if (brokerEmail == null) {
            log.warn("No broker email for shipment {}. Skipping alert.", shipment.getBlNumber());
            return;
        }

        emailService.sendDemurrageAlert(brokerEmail, shipment.getBlNumber(),
                daysRemaining, urgency);
    }

    private DemurrageUrgency classifyUrgency(long daysRemaining) {
        if (daysRemaining <= 0) return DemurrageUrgency.CRITICAL;
        if (daysRemaining <= 3) return DemurrageUrgency.WARNING;
        return DemurrageUrgency.SAFE;
    }
}
